name: Update
on:
  workflow_dispatch:
  schedule:
    # Runs weekly on Sunday at 00:00
    - cron: "0 0 * * 0"

jobs:
  nix-flake-update:
    name: Update Nix flake inputs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Determine Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v28
        with:
          pr-title: Update Nix flake inputs
          pr-labels: |
            dependencies
            automated
